# Generated by Django 6.0.3 on 2026-03-07 23:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicschedule',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
