# Generated by Django 6.0.3 on 2026-03-15 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_clinicschedule_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleappointment',
            name='average_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
        ),
    ]
