# Generated by Django 6.0.3 on 2026-03-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusuario',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
