# Generated by Django 6.0.3 on 2026-03-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customusuario_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
