# Generated by Django 6.0.3 on 2026-03-07 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customusuario_update_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthcareProfessional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('rg', models.CharField(blank=True, max_length=15, null=True)),
                ('board_number', models.CharField(max_length=20, verbose_name='Número do Conselho')),
                ('state_of_issue_UF', models.CharField(blank=True, max_length=3, null=True, verbose_name='Estado(UF) do Conselho')),
                ('digital_signature', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='customusuario',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
