# Generated by Django 6.0.3 on 2026-03-07 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_healthcareprofessional_patients_and_more'),
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcareprofessional',
            name='specialty',
            field=models.ManyToManyField(related_name='professionals', to='clinics.specialty'),
        ),
        migrations.AddField(
            model_name='healthcareprofessional',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patients',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL),
        ),
    ]
