# Generated by Django 6.0.3 on 2026-03-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_healthcareprofessional_specialty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
