# Generated by Django 6.0.3 on 2026-03-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_patients_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcareprofessional',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
