# Generated by Django 6.0.3 on 2026-03-07 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinical_notes', models.TextField(blank=True, null=True)),
                ('disease_history', models.TextField(blank=True, null=True)),
                ('physical_examination', models.TextField(blank=True, null=True)),
                ('service_Status', models.CharField(choices=[('ATENDIDO', 'Atendido'), ('FALTOU', 'Faltou'), ('REMARCAR', 'Remarcar')], default='ATENDIDO', max_length=15)),
                ('final_duration', models.DurationField(blank=True, null=True)),
                ('digital_signature', models.TextField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visualizar_agendamento', to='scheduling.scheduleappointment')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicines_name', models.CharField(max_length=255)),
                ('dosage', models.TextField(max_length=255)),
                ('frequency', models.TextField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizar_consulta', to='consultations.consultation')),
            ],
        ),
    ]
